# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbc98090d7816b9edd206dabe676df5a92d3baf7914166914ac243e0c1c0a19aa9d14ee0363b52d6ba72b753a08042c254f5cb9edc8e56160a8c8b60d4a6e1c2

test:
  secret_key_base: bb2f2acdb98f7001a90ddab635536a1ccfae7346db3bc21d82ffea9243babfb68029755db5623750ae286306bf87b221fb13bc011ccd60940b72cadcca433987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
